# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: internal_communication.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'internal_communication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cinternal_communication.proto\"\x07\n\x05\x45mpty\"H\n\x11TelemetryResponse\x12\x18\n\x10\x63urrent_latitude\x18\x01 \x01(\x01\x12\x19\n\x11\x63urrent_longitude\x18\x02 \x01(\x01\x32=\n\x0fInternalService\x12*\n\x0cGetTelemetry\x12\x06.Empty\x1a\x12.TelemetryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'internal_communication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=32
  _globals['_EMPTY']._serialized_end=39
  _globals['_TELEMETRYRESPONSE']._serialized_start=41
  _globals['_TELEMETRYRESPONSE']._serialized_end=113
  _globals['_INTERNALSERVICE']._serialized_start=115
  _globals['_INTERNALSERVICE']._serialized_end=176
# @@protoc_insertion_point(module_scope)
